{"name": "失败用例1/1 会触发TypeError", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'ZeroDivisionError'>", "trace": "self = <fixtureforassignments.testcase.test_calc.TestCalcuLator object at 0x7fcab5da1520>\na = '1', b = 1, errorType = 'TypeError'\ncalc_precedence = <fixtureforassignments.calculator.Calculator object at 0x7fcab5e12a30>\n\n    @allure.story('除法功能')\n    @allure.title('失败用例{a}/{b} 会触发{errorType}')\n    @pytest.mark.parametrize(**get_calc_data('div')['fail'])\n    def test_div_fail(self,a,b,errorType,calc_precedence):\n        with allure.step(f'计算{a}/{b}相除'):\n            logging.info(f'计算{a}/{b},预期结果为{errorType}异常')\n>       with pytest.raises(ZeroDivisionError,ValueError) as e:\nE       Failed: DID NOT RAISE <class 'ZeroDivisionError'>\n\ntest_calc.py:89: Failed"}, "steps": [{"name": "计算1/1相除", "status": "passed", "start": 1627228335335, "stop": 1627228335336}], "attachments": [{"name": "log", "source": "6907b60c-8a19-453b-b51f-6533c78aa945-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "'1'"}, {"name": "b", "value": "1"}, {"name": "errorType", "value": "'TypeError'"}], "start": 1627228335335, "stop": 1627228335336, "uuid": "643e74c9-afd0-4e03-a47a-92adeee9b435", "historyId": "d605b0aa11043f60eeab9edbbd79180f", "testCaseId": "3469bee631d46de5cdeb7268ac732a4d", "fullName": "test_div_fail[æ°å­åéæ°å­ç¸é¤]#test_div_fail", "labels": [{"name": "story", "value": "除法功能"}, {"name": "feature", "value": "计算器"}, {"name": "suite", "value": "test_div_fail[æ°å­åéæ°å­ç¸é¤]"}, {"name": "host", "value": "liuyaodeiMac.local"}, {"name": "thread", "value": "10871-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_div_fail[æ°å­åéæ°å­ç¸é¤]"}]}