INFO     root:conftest.py:13 开始计算
INFO     root:test_calc.py:46 计算a+1,预期结果为TypError异常
INFO     root:conftest.py:16 结束运算